//*****************************************************************************
//*****************************************************************************
//  FILENAME:  Amp_Vac.h
//  Version: 2.0, Updated on 2003/08/28 at 17:09:28
//  Generated by PSoC Designer ver 4.0 b865 : 27 August, 2003
//
//  DESCRIPTION: C declarations for a two-OpAmp Instrumentation Amplifier
//               topology in the 22/24/27/28xxx family of PSoC devices
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress MicroSystems 2001-2003. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall Amp_Vac_Start
#pragma fastcall Amp_Vac_SetPower
#pragma fastcall Amp_Vac_SetGain
#pragma fastcall Amp_Vac_Stop

//-------------------------------------------------
// Prototypes of the Amp_Vac API.
//-------------------------------------------------
extern void Amp_Vac_Start(BYTE bPower);
extern void Amp_Vac_SetPower(BYTE bPower);
extern void Amp_Vac_SetGain(BYTE bGain);
extern void Amp_Vac_Stop(void);

//-------------------------------------------------
// Defines for Amp_Vac API's.
//-------------------------------------------------
#define Amp_Vac_OFF         0
#define Amp_Vac_LOWPOWER    1
#define Amp_Vac_MEDPOWER    2
#define Amp_Vac_HIGHPOWER   3

#define Amp_Vac_G16_0  0x00
#define Amp_Vac_G8_00  0x10
#define Amp_Vac_G5_33  0x20
#define Amp_Vac_G4_00  0x30
#define Amp_Vac_G3_20  0x40
#define Amp_Vac_G2_67  0x50
#define Amp_Vac_G2_27  0x60
#define Amp_Vac_G2_00  0x70


//-------------------------------------------------
// Hardware Register Definitions
//-------------------------------------------------

#pragma ioport  Amp_Vac_INV_CR0:    0x075
BYTE            Amp_Vac_INV_CR0;
#pragma ioport  Amp_Vac_INV_CR1:    0x076
BYTE            Amp_Vac_INV_CR1;
#pragma ioport  Amp_Vac_INV_CR2:    0x077
BYTE            Amp_Vac_INV_CR2;
#pragma ioport  Amp_Vac_INV_CR3:    0x074
BYTE            Amp_Vac_INV_CR3;

#pragma ioport  Amp_Vac_NON_INV_CR0:    0x071
BYTE            Amp_Vac_NON_INV_CR0;
#pragma ioport  Amp_Vac_NON_INV_CR1:    0x072
BYTE            Amp_Vac_NON_INV_CR1;
#pragma ioport  Amp_Vac_NON_INV_CR2:    0x073
BYTE            Amp_Vac_NON_INV_CR2;
#pragma ioport  Amp_Vac_NON_INV_CR3:    0x070
BYTE            Amp_Vac_NON_INV_CR3;


// end of file Amp_Vac.h
