//*****************************************************************************
//*****************************************************************************
//  FILENAME:  AMUX4_1.h
//  Version: 1.1, Updated on 2003/08/20 at 20:37:14
//  Generated by PSoC Designer ver 4.0 b865 : 27 August, 2003
//
//  DESCRIPTION:  AMux4 User Module C Language interface file for the
//                22/24/25/26/27xxx PSoC family of devices.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress MicroSystems 2000-2003. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************


#include <m8c.h>
//-------------------------------------------------
// Defines for AMUX4_1 API's.
//-------------------------------------------------
#define AMUX4_1_PORT0_0                0x00
#define AMUX4_1_PORT0_2                0x01
#define AMUX4_1_PORT0_4                0x02
#define AMUX4_1_PORT0_6                0x03

#define AMUX4_1_PORT0_1                0x00
#define AMUX4_1_PORT0_3                0x01
#define AMUX4_1_PORT0_5                0x02
#define AMUX4_1_PORT0_7                0x03


#pragma fastcall AMUX4_1_InputSelect
#pragma fastcall AMUX4_1_Start
#pragma fastcall AMUX4_1_Stop 

//-------------------------------------------------
// Prototypes of the AMUX4_1 API.
//-------------------------------------------------

extern void AMUX4_1_InputSelect(BYTE bChannel);
extern void AMUX4_1_Start(void);
extern void AMUX4_1_Stop(void);

// end of file AMUX4_1.h
