//*****************************************************************************
//*****************************************************************************
//  FILENAME: Count_I.h
//   Version: 2.1, Updated on 2003/08/26 at 16:04:39
//  Generated by PSoC Designer ver 4.0 b865 : 27 August, 2003
//
//  DESCRIPTION: Counter8 User Module C Language interface file
//               for the 22/24/27/28xxx PSoC family of devices
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress MicroSystems 2000-2003. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall Count_I_EnableInt
#pragma fastcall Count_I_DisableInt
#pragma fastcall Count_I_Start
#pragma fastcall Count_I_Stop
#pragma fastcall Count_I_bReadCounter              // Read  DR0
#pragma fastcall Count_I_WritePeriod               // Write DR1
#pragma fastcall Count_I_bReadCompareValue         // Read  DR2
#pragma fastcall Count_I_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall bCount_I_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall bCount_I_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the Count_I API.
//-------------------------------------------------

extern void Count_I_EnableInt(void);
extern void Count_I_DisableInt(void);
extern void Count_I_Start(void);
extern void Count_I_Stop(void);
extern BYTE Count_I_bReadCounter(void);
extern void Count_I_WritePeriod(BYTE bPeriod);
extern BYTE Count_I_bReadCompareValue(void);
extern void Count_I_WriteCompareValue(BYTE bCompareValue);

// The following functions are deprecated.
// They may be omitted in future releases
//
extern BYTE bCount_I_ReadCounter(void);            // Deprecated
extern BYTE bCount_I_ReadCompareValue(void);       // Deprecated


//--------------------------------------------------
// Constants for Count_I API's.
//--------------------------------------------------

#define Count_I_CONTROL_REG_START_BIT          ( 0x01 )
#define Count_I_INT_REG_ADDR                   ( 0x0e1 )
#define Count_I_INT_MASK                       ( 0x01 )


//-------------------------------------------------
// Register Addresses for Count_I
//-------------------------------------------------

#pragma ioport  Count_I_COUNTER_REG:    0x020              //DR0 Count register
BYTE            Count_I_COUNTER_REG;
#pragma ioport  Count_I_PERIOD_REG: 0x021                  //DR1 Period register
BYTE            Count_I_PERIOD_REG;
#pragma ioport  Count_I_COMPARE_REG:    0x022              //DR2 Compare register
BYTE            Count_I_COMPARE_REG;
#pragma ioport  Count_I_CONTROL_REG:    0x023              //Control register
BYTE            Count_I_CONTROL_REG;
#pragma ioport  Count_I_FUNC_REG:   0x120                  //Function register
BYTE            Count_I_FUNC_REG;
#pragma ioport  Count_I_INPUT_REG:  0x121                  //Input register
BYTE            Count_I_INPUT_REG;
#pragma ioport  Count_I_OUTPUT_REG: 0x122                  //Output register
BYTE            Count_I_OUTPUT_REG;
#pragma ioport  Count_I_INT_REG:       0x0e1               //Interrupt Mask Register
BYTE            Count_I_INT_REG;


//-------------------------------------------------
// Count_I Macro 'Functions'
//-------------------------------------------------

#define Count_I_Start_M \
   Count_I_CONTROL_REG |=  Count_I_CONTROL_REG_START_BIT

#define Count_I_Stop_M  \
   Count_I_CONTROL_REG &= ~Count_I_CONTROL_REG_START_BIT

#define Count_I_EnableInt_M   \
   M8C_EnableIntMask(Count_I_INT_REG, Count_I_INT_MASK)

#define Count_I_DisableInt_M  \
   M8C_DisableIntMask(Count_I_INT_REG, Count_I_INT_MASK)


// end of file Count_I.h
