//*****************************************************************************
//*****************************************************************************
//  FILENAME: FlashTemp_1.h
//   Version: 2.0, Updated on 2003/08/19 at 20:44:15
//  Generated by PSoC Designer ver 4.0 b865 : 27 August, 2003
//
//  DESCRIPTION: FlashTemp User Module C Language interface file for the
//               22/24/25/26/27xxx PSoC family of devices.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress MicroSystems 2000-2003. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#include <M8C.h>

#pragma fastcall FlashTemp_1_Start
#pragma fastcall FlashTemp_1_fIsData
#pragma fastcall FlashTemp_1_cGetData
#pragma fastcall FlashTemp_1_Stop

//-------------------------------------------------
// Prototypes of the FlashTemp_1 API.
//-------------------------------------------------
extern void FlashTemp_1_Start(void);
extern CHAR FlashTemp_1_fIsData(void);
extern CHAR FlashTemp_1_cGetData(void);
extern void FlashTemp_1_Stop(void);

//-------------------------------------------------
// Do not use! For backwards compatibility only.
#pragma fastcall fFlashTemp_1_IsData
#pragma fastcall cFlashTemp_1_GetData
extern CHAR fFlashTemp_1_IsData(void);
extern CHAR cFlashTemp_1_GetData(void);
//-------------------------------------------------

//-------------------------------------------------
// Register Addresses for FlashTemp_1
//-------------------------------------------------
#pragma ioport  FlashTemp_1_FlashTempCR0:   0x094
BYTE            FlashTemp_1_FlashTempCR0;
#pragma ioport  FlashTemp_1_FlashTempCR1:   0x095
BYTE            FlashTemp_1_FlashTempCR1;
#pragma ioport  FlashTemp_1_FlashTempCR2:   0x096
BYTE            FlashTemp_1_FlashTempCR2;
#pragma ioport  FlashTemp_1_FlashTempCR3:   0x097
BYTE            FlashTemp_1_FlashTempCR3;

// end of file FlashTemp_1.h
