//*****************************************************************************
//*****************************************************************************
//  FILENAME:  Limit_I.h
//  Version: 3.0, Updated on 2003/08/27 at 14:02:42
//  Generated by PSoC Designer ver 4.0 b865 : 27 August, 2003
//
//  DESCRIPTION:  CMPPRG User Module C Language interface file for the
//                22/24/27xxx PSoC family of devices.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress MicroSystems 2000-2003. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <M8C.h>

//-------------------------------------------------
// Defines for Limit_I API's.
//-------------------------------------------------
#define Limit_I_OFF         0
#define Limit_I_LOWPOWER    1
#define Limit_I_MEDPOWER    2
#define Limit_I_HIGHPOWER   3

#define Limit_I_REF1_000   0xf0
#define Limit_I_REF0_937   0xe0 
#define Limit_I_REF0_875   0xd0
#define Limit_I_REF0_812   0xc0
#define Limit_I_REF0_750   0xb0
#define Limit_I_REF0_688   0xa0
#define Limit_I_REF0_625   0x90
#define Limit_I_REF0_562   0x80
#define Limit_I_REF0_500   0x70
#define Limit_I_REF0_437   0x60
#define Limit_I_REF0_375   0x50
#define Limit_I_REF0_312   0x40
#define Limit_I_REF0_250   0x30
#define Limit_I_REF0_188   0x20
#define Limit_I_REF0_125   0x10
#define Limit_I_REF0_062   0x00
#define Limit_I_REF0_042   0x14
#define Limit_I_REF0_021   0x04


#pragma fastcall Limit_I_Start
#pragma fastcall Limit_I_SetPower
#pragma fastcall Limit_I_SetRef 
#pragma fastcall Limit_I_Stop

//-------------------------------------------------
// Prototypes of the Limit_I API.
//-------------------------------------------------
extern void Limit_I_Start(BYTE bPowerSetting);
extern void Limit_I_SetPower(BYTE bPowerSetting);
extern void Limit_I_SetRef(BYTE bRefValue);
extern void Limit_I_Stop(void);

//-------------------------------------------------
// Hardware Register Definitions
//-------------------------------------------------
#pragma ioport  Limit_I_COMP_CR0:   0x07d
BYTE            Limit_I_COMP_CR0;
#pragma ioport  Limit_I_COMP_CR1:   0x07e
BYTE            Limit_I_COMP_CR1;
#pragma ioport  Limit_I_COMP_CR2:   0x07f
BYTE            Limit_I_COMP_CR2;
#pragma ioport  Limit_I_COMP_CR3:   0x07c
BYTE            Limit_I_COMP_CR3;

// end of file Limit_I.h
