; Generated by PSoC Designer ver 4.0 b865 : 27 August, 2003
;
;
;  pumpDynamic.asm
;
;  Data: 29 October, 2001
;  Copyright Cypress MicroSystems 2001
;
;  This file is generated by the Device Editor on Application Generation.
;  It contains functions that can be used to test the state of the 
;  currently active configuration.
;  
;  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
;  Edits to this file will not be preserved.
;
include "PSoCDynamic.inc"
export IspumpLoaded
export _IspumpLoaded
export IsAGNDLoaded
export _IsAGNDLoaded
IspumpLoaded:
_IspumpLoaded:
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+pump_ADDR_OFF], pump_BIT
	jz		pumpIsNotLoaded
	mov		a, 1
pumpIsNotLoaded:
	ret

IsAGNDLoaded:
_IsAGNDLoaded:
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+AGND_ADDR_OFF], AGND_BIT
	jz		AGNDIsNotLoaded
	mov		a, 1
AGNDIsNotLoaded:
	ret

