/******************************************************************************
*  Generated by PSoC Designer ver 4.0 b865 : 27 August, 2003
******************************************************************************/
extern void LoadConfig_pump( void);
extern void UnloadConfig_pump( void);
extern char IspumpLoaded( void);
extern void LoadConfig_AGND( void);
extern void UnloadConfig_AGND( void);
extern char IsAGNDLoaded( void);
extern void UnloadConfig_Total( void);
