//*****************************************************************************
//*****************************************************************************
//  FILENAME: PWM_PH_B.h
//   Version: 2.2, Updated on 2003/08/26 at 16:06:22
//  Generated by PSoC Designer ver 4.0 b865 : 27 August, 2003
//
//  DESCRIPTION: PWMDB8 User Module C Language interface file
//               for the 22/24/25/26/27xxx) PSoC family of devices
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress MicroSystems 2000-2003. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall  PWM_PH_B_EnableInt
#pragma fastcall  PWM_PH_B_DisableInt
#pragma fastcall  PWM_PH_B_Start
#pragma fastcall  PWM_PH_B_Stop
#pragma fastcall  PWM_PH_B_WritePeriod
#pragma fastcall  PWM_PH_B_WritePulseWidth
#pragma fastcall  PWM_PH_B_WriteDeadTime
#pragma fastcall  PWM_PH_B_bReadPulseWidth

//-------------------------------------------------
// Prototypes of the PWM_PH_B API.
//-------------------------------------------------
extern void  PWM_PH_B_EnableInt(void);
extern void  PWM_PH_B_DisableInt(void);
extern void  PWM_PH_B_Start(void);
extern void  PWM_PH_B_Stop(void);
extern void  PWM_PH_B_WritePeriod(BYTE bPeriod);
extern void  PWM_PH_B_WritePulseWidth(BYTE bPulseWidth);
extern void  PWM_PH_B_WriteDeadTime(BYTE bDeadTime);
extern BYTE  PWM_PH_B_bReadPulseWidth(void);	

//-------------------------------------------------
// Do not use! For backwards compatibility only.
#pragma fastcall bPWM_PH_B_ReadPulseWidth
extern BYTE bPWM_PH_B_ReadPulseWidth(void);	
//-------------------------------------------------

//-------------------------------------------------
// Register Addresses for PWM_PH_B
//-------------------------------------------------
#pragma ioport  PWM_PH_B_PWM_CONTROL_REG:   0x02b          //PWM Control register
BYTE            PWM_PH_B_PWM_CONTROL_REG;
#pragma ioport  PWM_PH_B_PWM_COUNTER_REG:   0x028          //PWM Counter register
BYTE            PWM_PH_B_PWM_COUNTER_REG;
#pragma ioport  PWM_PH_B_PWM_PERIOD_REG:    0x029          //PWM Period value register
BYTE            PWM_PH_B_PWM_PERIOD_REG;
#pragma ioport  PWM_PH_B_PULSE_WIDTH_REG:   0x02a          //PWM PulseWidth register
BYTE            PWM_PH_B_PULSE_WIDTH_REG;
#pragma ioport  PWM_PH_B_PWM_FUNC_REG:  0x128              //Function register
BYTE            PWM_PH_B_PWM_FUNC_REG;
#pragma ioport  PWM_PH_B_PWM_INPUT_REG: 0x129              //Input register
BYTE            PWM_PH_B_PWM_INPUT_REG;
#pragma ioport  PWM_PH_B_PWM_OUTPUT_REG:    0x12a          //Output register
BYTE            PWM_PH_B_PWM_OUTPUT_REG;
#pragma ioport  PWM_PH_B_DB_CONTROL_REG:    0x02f          //DB Control register
BYTE            PWM_PH_B_DB_CONTROL_REG; 
#pragma ioport  PWM_PH_B_DB_COUNTER_REG:    0x02c          //DB Counter register
BYTE            PWM_PH_B_DB_COUNTER_REG; 
#pragma ioport  PWM_PH_B_DEAD_TIME_REG: 0x02d              //DB Dead Timer register
BYTE            PWM_PH_B_DEAD_TIME_REG; 
#pragma ioport  PWM_PH_B_DB_FUNC_REG:   0x12c              //Function register
BYTE            PWM_PH_B_DB_FUNC_REG; 
#pragma ioport  PWM_PH_B_DB_INPUT_REG:  0x12d              //Input register
BYTE            PWM_PH_B_DB_INPUT_REG;  
#pragma ioport  PWM_PH_B_DB_OUTPUT_REG: 0x12e              //Output register
BYTE            PWM_PH_B_DB_OUTPUT_REG; 

// end of file PWM_PH_B.h
