//*****************************************************************************
//*****************************************************************************
//  FILENAME: PWM_PH_A.h
//   Version: 2.2, Updated on 2003/08/26 at 16:06:22
//  Generated by PSoC Designer ver 4.0 b865 : 27 August, 2003
//
//  DESCRIPTION: PWMDB8 User Module C Language interface file
//               for the 22/24/25/26/27xxx) PSoC family of devices
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress MicroSystems 2000-2003. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall  PWM_PH_A_EnableInt
#pragma fastcall  PWM_PH_A_DisableInt
#pragma fastcall  PWM_PH_A_Start
#pragma fastcall  PWM_PH_A_Stop
#pragma fastcall  PWM_PH_A_WritePeriod
#pragma fastcall  PWM_PH_A_WritePulseWidth
#pragma fastcall  PWM_PH_A_WriteDeadTime
#pragma fastcall  PWM_PH_A_bReadPulseWidth

//-------------------------------------------------
// Prototypes of the PWM_PH_A API.
//-------------------------------------------------
extern void  PWM_PH_A_EnableInt(void);
extern void  PWM_PH_A_DisableInt(void);
extern void  PWM_PH_A_Start(void);
extern void  PWM_PH_A_Stop(void);
extern void  PWM_PH_A_WritePeriod(BYTE bPeriod);
extern void  PWM_PH_A_WritePulseWidth(BYTE bPulseWidth);
extern void  PWM_PH_A_WriteDeadTime(BYTE bDeadTime);
extern BYTE  PWM_PH_A_bReadPulseWidth(void);	

//-------------------------------------------------
// Do not use! For backwards compatibility only.
#pragma fastcall bPWM_PH_A_ReadPulseWidth
extern BYTE bPWM_PH_A_ReadPulseWidth(void);	
//-------------------------------------------------

//-------------------------------------------------
// Register Addresses for PWM_PH_A
//-------------------------------------------------
#pragma ioport  PWM_PH_A_PWM_CONTROL_REG:   0x03b          //PWM Control register
BYTE            PWM_PH_A_PWM_CONTROL_REG;
#pragma ioport  PWM_PH_A_PWM_COUNTER_REG:   0x038          //PWM Counter register
BYTE            PWM_PH_A_PWM_COUNTER_REG;
#pragma ioport  PWM_PH_A_PWM_PERIOD_REG:    0x039          //PWM Period value register
BYTE            PWM_PH_A_PWM_PERIOD_REG;
#pragma ioport  PWM_PH_A_PULSE_WIDTH_REG:   0x03a          //PWM PulseWidth register
BYTE            PWM_PH_A_PULSE_WIDTH_REG;
#pragma ioport  PWM_PH_A_PWM_FUNC_REG:  0x138              //Function register
BYTE            PWM_PH_A_PWM_FUNC_REG;
#pragma ioport  PWM_PH_A_PWM_INPUT_REG: 0x139              //Input register
BYTE            PWM_PH_A_PWM_INPUT_REG;
#pragma ioport  PWM_PH_A_PWM_OUTPUT_REG:    0x13a          //Output register
BYTE            PWM_PH_A_PWM_OUTPUT_REG;
#pragma ioport  PWM_PH_A_DB_CONTROL_REG:    0x03f          //DB Control register
BYTE            PWM_PH_A_DB_CONTROL_REG; 
#pragma ioport  PWM_PH_A_DB_COUNTER_REG:    0x03c          //DB Counter register
BYTE            PWM_PH_A_DB_COUNTER_REG; 
#pragma ioport  PWM_PH_A_DEAD_TIME_REG: 0x03d              //DB Dead Timer register
BYTE            PWM_PH_A_DEAD_TIME_REG; 
#pragma ioport  PWM_PH_A_DB_FUNC_REG:   0x13c              //Function register
BYTE            PWM_PH_A_DB_FUNC_REG; 
#pragma ioport  PWM_PH_A_DB_INPUT_REG:  0x13d              //Input register
BYTE            PWM_PH_A_DB_INPUT_REG;  
#pragma ioport  PWM_PH_A_DB_OUTPUT_REG: 0x13e              //Output register
BYTE            PWM_PH_A_DB_OUTPUT_REG; 

// end of file PWM_PH_A.h
