//*****************************************************************************
//*****************************************************************************
//  FILENAME:  RefAGND.h
//  Version: 1.1, Updated on 2003/08/19 at 20:48:24
//  Generated by PSoC Designer ver 4.0 b865 : 27 August, 2003
//
//  DESCRIPTION:
//  DESCRIPTION: RefMux User Module C Language interface file for the
//               22/24/27xxx PSoC family of devices.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress MicroSystems 2001-2003. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#include <m8c.h>

//-------------------------------------------------
// Constants for RefAGND API's.
//-------------------------------------------------
#define RefAGND_MUXOFF                 0x00
#define RefAGND_PMUXOUT                0x10
#define RefAGND_AGND                   0x14
#define RefAGND_REFLO                  0x18
#define RefAGND_REFHI                  0x1C

#define RefAGND_OFF                    0
#define RefAGND_LOWPOWER               1
#define RefAGND_MEDPOWER               2
#define RefAGND_HIGHPOWER              3


#pragma fastcall RefAGND_Start
#pragma fastcall RefAGND_SetPower
#pragma fastcall RefAGND_Stop
#pragma fastcall RefAGND_RefSelect

//-------------------------------------------------
// Prototypes of the RefAGND API.
//-------------------------------------------------
extern void RefAGND_Start(BYTE bPower);
extern void RefAGND_SetPower(BYTE bPower);
extern void RefAGND_Stop( void );
extern void RefAGND_RefSelect(BYTE bRef);


//-------------------------------------------------
// Register Addresses for RefAGND
//-------------------------------------------------

#pragma ioport  RefAGND_REFMUX_CR0: 0x079
BYTE            RefAGND_REFMUX_CR0;
#pragma ioport  RefAGND_REFMUX_CR1: 0x07a
BYTE            RefAGND_REFMUX_CR1;
#pragma ioport  RefAGND_REFMUX_CR2: 0x07b
BYTE            RefAGND_REFMUX_CR2;
#pragma ioport  RefAGND_REFMUX_CR3: 0x078
BYTE            RefAGND_REFMUX_CR3;

// end of file RefAGND.
